### ISSUE TITLE
Lifetime hints?

### ISSUE THREAD

**Issue by tomaszmrugalski** [dhcwg/dhcp-mac#8]
There's a case of certain devices that have specific time span, e.g. non-rechargeable medical sensors that have a lifetime of 5 hours. Would it be useful for those devices to send valid-lifetime hints to the server? It doesn't make sense to assign an addresses for weeks if the device shuts down permanently in hours.

**Comment by bevolz** [comment]
While I'm OK with allowing, I do have concerns that clients may misuse this and specify the remaining lifetime instead of the "requested" and I'd prefer the server use other mechanisms to determine the "type of client" to provide the proper lifetimes.

Perhaps if we allow, we should make it clear that:
1. Client MUST NOT return the remaining lifetime but the "requested" lifetime.
2. Servers SHOULD use other mechanisms (such as user-class, vendor options, etc.) to determine the device type and appropriate lifetimes.

**Comment by helinhl** [comment]
Support allowing. But we should specify how to deal with these hints. Agree with Bernie's suggestion that server use other mechanisms to determine the type of client to provide proper lifetimes.

**Comment by tomaszmrugalski** [comment]
Fair enough. Removed comment in the xml that suggested we need to explore this. I don't think we need to explain how servers can use user-class, vendor info (or basically fingerprinting the client) to make determination of appropriate lifetimes. This is a generic policy problem and it's always been out of scope for RFCs.

So no text needed.

**Comment by bevolz** [comment]
Agree! Less is more.
